#include "defines.h"

#ifdef PC
  #include <stdio.h>
  #include "pc/pc.h"
#else
  #include "system/32x.h"
  #include "system/hw_32x.h"
  #include "system/32x_custom.h"
#endif

#include "structs.h"
#include "engine_defines.h"
#include "scene_defines.h"
#include "engine_globals.h"
#include "engine_init.h"
#include "scene.h"
#include "engine_update.h"
#include "draw_scene.h"
#include "engine/math_c.h"
#include "engine/utils.h"
#include "engine/div_lut.h"
#include "engine/lut.h"
#include "engine/subdiv_lut.h"
#include "engine/clipping.h"
#include "engine/frustum.h"
#include "engine/matrix.h"
#include "engine/setup.h"
#include "engine/transforms.h"
#include "engine/visibility.h"
#include "engine/process_faces.h"
#include "engine/drawing.h"
#include "engine/subdiv_face.h"
#include "engine/raster.h"
#include "engine/raster_zb.h"
// #include "engine/raster_occ.h"
#include "engine/render_voxel.h"
#include "engine/frustum_cl_grid.h"
#include "engine/font.h"
#include "engine/text.h"
#include "asm/asm_function_defines.h"